### ISSUE TITLE
Kernel Panic if function implementing Scheme panics

### ISSUE THREAD

**Issue by MggMuggins** [redox-os/kernel#68]
So I've been playing around with schemes, and I was being able to cause a kernel panic from userspace, basically...

Anyway, I had some faulty logic that was causing my `open` to panic. Here's the stripped down version on how to reproduce:
```Rust
impl Scheme for MyScheme {
    fn open(&self, path: &[u8], uid: u32, gid: u32) -> Result<usize> {
        panic!("Hi!");
        Ok(0) // <- Unreachable???
    }
}
```
Whip that up into a daemon that looks like the `main.rs` [here](https://gist.github.com/MggMuggins/2124a135e515a4568ca3e1e744598241) and you get a nce kernel panic whenever you try to cat anything from your scheme...

My guess is that it's an issue with the root scheme not being able to understand a `read` not being followed by a `write`, but I'm not particularly sure on that.

**Comment by jackpot51** [comment]
Are you sure it was a kernel panic? Can you provide the panic dump?

**Comment by NilSet** [comment]
Panic dump in the linked gist

**Comment by MggMuggins** [comment]
If I remove the call to `setrens` it does not panic.

**Comment by NilSet** [comment]
It's definitely panicking on unwrapping the current namespace's scheme mapping.
```
#0  kernel::panic::rust_begin_unwind (fmt=..., 
    file=..., line=<optimized out>)
    at src/panic.rs:20
#1  0xffffff00001a2144 in core::panicking::panic_fmt ()
#2  0xffffff00001a21b9 in core::option::expect_failed ()
#3  0xffffff0000183d5a in core::option::Option<&alloc::btree::map::BTreeMap<alloc::boxed::Box<[u8]>, kernel::scheme::SchemeId>>::expect<&alloc::btree::map::BTreeMap<alloc::boxed::Box<[u8]>, kernel::scheme::SchemeId>> (msg=..., self=...)
    at /home/nullset/rust/redox-os/redox/rust/src/libcore/option.rs:302
#4  alloc::btree::map::{{impl}}::index<kernel::scheme::SchemeNamespace,kernel::scheme::SchemeNamespace,alloc::btree::map::BTreeMap<alloc::boxed::Box<[u8]>, kernel::scheme::SchemeId>> (self=<optimized out>, 
    key=<optimized out>)
    at /home/nullset/rust/redox-os/redox/rust/src/liballoc/btree/map.rs:1753
#5  kernel::scheme::SchemeList::get_name (
    self=0xffffff00009155b0 <kernel::scheme::SCHEMES+16>, ns=..., name=...) at src/scheme/mod.rs:181
#6  0xffffff0000185c47 in kernel::syscall::fs::open
    (path=..., flags=16843190)
    at src/syscall/fs.rs:105
#7  0xffffff0000191c76 in kernel::syscall::syscall::inner (a=<optimized out>, b=<optimized out>, 
    d=16843190, f=<optimized out>, 
    bp=<optimized out>, c=<optimized out>, 
    e=<optimized out>, stack=<optimized out>)
    at src/syscall/mod.rs:73
#8  kernel::syscall::syscall (
    a=18446742974199663024, b=549755817200, c=18, 
    d=16843190, e=549755817200, 
    f=18446742974207421986, bp=<optimized out>, 
    stack=<optimized out>)
    at src/syscall/mod.rs:180
#9  0xffffff0000125f07 in kernel::arch::x86_64::interrupt::syscall::syscall::inner (stack=0x110000)
    at src/arch/x86_64/interrupt/syscall.rs:16
#10 0xffffff0000125ec0 in kernel::arch::x86_64::interrupt::syscall::syscall ()
    at src/arch/x86_64/interrupt/syscall.rs:40
#11 0x0000000000000033 in ?? ()
#12 0x0000000000000065 in ?? ()
#13 0x0000000000000000 in ?? ()
```

**Comment by NilSet** [comment]
All it takes is to switch to ns 0 and then try to use a scheme to cause this kernel panic. I think the userspace panic code must be trying to open up some file which trips this?

**Comment by jackpot51** [comment]
Good catch @nilset!
